- hosts: localhost

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: config.yml
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['appstore']

    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/terminal.yml
      tags: ['terminal']
    
    - import_tasks: tasks/build-from-source.yml
      tags: ['extra-packages']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']

    - import_tasks: tasks/macos.yml
      tags: ['macos']
