# nnn
- name: Install dependencies for build
  community.general.homebrew:
    name:
      - readline
      - ncurses
      - pkg-config
    state: present
- name: Clone nnn
  ansible.builtin.git:
    repo: https://github.com/jarun/nnn.git
    dest: /tmp/nnn
- name: Build nnn
  become: true
  make:
    chdir: /tmp/nnn
    target: all
    params:
      0_NERD: 1 # This option enables icon support
- name: Copy nnn binary
  become: true
  copy:
    src: /tmp/nnn/nnn
    dest: /usr/local/bin

# dark-mode-notify
- name: Clone dark-mode-notify
  ansible.builtin.git:
    repo: https://github.com/bouk/dark-mode-notify
    dest: /tmp/dark-mode-notify
- name: Build dark-mode-notify
  become: true
  ansible.builtin.shell: swiftc dark-mode-notify.swift -o /usr/local/bin/dark-mode-notify
  args:
    chdir: /tmp/dark-mode-notify
