- name: Check if dotfiles folder exists
  ansible.builtin.stat:
    path: "{{ dotfiles_repo_local_destination }}"
  register: repo_check
- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
  when: not repo_check.stat.exists
- name: Install stow
  community.general.homebrew:
    name: stow
    state: present
- name: Install dotfiles
  script: "{{dotfiles_repo_local_destination}}/install.sh"
- name: Init git-secrets
  shell: git secrets --register-aws --global
