- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}" 
- name: Install stew
  community.general.homebrew:
    name: stew
    state: present
- name: Install dotfiles
  script: "{{dotfiles_repo_local_destination}}/install.sh"
- name: Init git-secrets
  shell: git secrets --register-aws --global
