- name: Check if dotfiles folder exists
  ansible.builtin.stat:
    path: "{{ dotfiles_repo_local_destination }}"
  register: repo_check
- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
  when: not repo_check.stat.exists
- name: Install stow
  community.general.homebrew:
    name: stow
    state: present
- name: Install dotfiles
  script: "{{dotfiles_repo_local_destination}}/install.sh"
- name: Init git-secrets
  shell: git secrets --register-aws --global
- name: Creat symlinks for NeoVim
  ansible.builtin.file:
    src: ~/.vim
    dest: ~/.neovim
    state: link
- name: Download vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
    force: true
- name: Make sure that plugged folder exists
  ansible.builtin.file:
    dest: ~/.vim/plugged
    state: directory
- name: Creat symlink for autoload (vim-plugged)
  ansible.builtin.file:
    src: ~/.vim/autoload
    dest: ~/.config/nvim/autoload
    state: link
- name: Install vim plugins
  shell: vim +'PlugInstall --sync' +qa
