- name: Ensure .ssh directory exists
  ansible.builtin.file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory

- name: Install ssh key
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0400
  tags: ["vault"]

- name: Install ssh public key
  ansible.builtin.copy:
    src: "{{ source_key_pub }}"
    dest: "{{ dest_key_pub }}"
    mode: 0644
  tags: ["vault"]

- name: Add SSH authorized key for current user
  ansible.posix.authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ dest_key_pub }}"
  with_fileglob:
    - ~/.ssh/*.pub
  tags: ["vault"]
